### PR TITLE
Tag push fix

### LINKED ISSUE #75: Issues with automatic tag push
When delivering a version, git-deliver tries to detect if a tag exists for the revison and tries to push it along : 

https://github.com/arnoo/git-deliver/blob/master/deliver.sh#L930

``` bash
local tags=$(git show-ref --tags -d | grep "^$VERSION_SHA" | cut -d" " -f2 | sed -e 's,refs/tags/,,g' | grep -v ^delivered-)
if [[ "$tags" != "" ]]; then
    run "git push $force \"$REMOTE\" tag $tags"
    exit_if_error 13
fi
```

I just found two issues with this : 
## Error if two or more tags exist

Only the first tag is pushed, the next ones are launch as commands (which obviously fail... or could do funny stuff :stuck_out_tongue_winking_eye: )

```
To ssh://user@example.net/my/repo
 * [new tag]         tag1 -> tag1
bash: line 1: tag2: command not found
```
## Error for dereferenced tags

The "^{}" suffix is not stripped out : 

```
fatal: remote part of refspec is not a valid name in refs/tags/tag1^{}
```

### PR DESCRIPTION
**Pull request by Djuuu**
Fixes #75 : Issues with automatic tag push : 
* pushes multiple tags
* strips "^{}" suffix for dereferenced tags

### CODE REVIEW

**Comment by arnoo** [comment]
Awesome, thanks !
I suppose you tested this on Windows ?

**Comment by Djuuu** [comment]
Yes, I tested it on Windows (with _msys_ and _cygwin_).
The tests were also implemented and tested on Linux.

**Comment by Djuuu** [comment]
I basically used the line you use higher up in `function remote_status` (only separating tags with spaces instead of commas).

**Comment by arnoo** [comment]
Great, thanks a lot !

**Pull request merged**
